#!/usr/bin/env bash
# push.sh — 一次性完成所有事 (推送 + 开 Pages + 保存凭据到 macOS 钥匙串)
# 用法: ./push.sh YOUR_GITHUB_TOKEN
#
#   生成 token: 浏览器打开 https://github.com/settings/tokens/new
#     Note: push
#     Expiration: No expiration
#     Scopes: 勾 repo
#     Generate token, 复制那串字符
#
# 跑完这一次, 以后改完内容只需:
#   ./deploy.sh "msg"
# (不需要再 paste token)

set -e

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
ok()   { printf "${GREEN}[OK]${NC} %s\n" "$*"; }
warn() { printf "${YELLOW}[WARN]${NC} %s\n" "$*"; }
err()  { printf "${RED}[ERR]${NC} %s\n" "$*"; }

SITE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SITE_DIR"

USER="huang-yu-an"
REPO="${USER}.github.io"
KEYCHAIN_SERVICE="github.com"
KEYCHAIN_ACCOUNT="$USER"

# ---- 0. 拿 token (参数 > 钥匙串 > 询问) --------------------------------
TOKEN="$1"
if [ -z "$TOKEN" ]; then
    # Try macOS keychain
    TOKEN=$(security find-generic-password -s "$KEYCHAIN_SERVICE" -a "$KEYCHAIN_ACCOUNT" -w 2>/dev/null || true)
fi
if [ -z "$TOKEN" ]; then
    err "没找到 token"
    echo ""
    echo "用法 1 (推荐): ./push.sh ghp_你的token"
    echo "用法 2: 先把 token 存到 macOS 钥匙串, 然后 ./push.sh"
    echo "        security add-generic-password -s github.com -a $USER -w 'ghp_你的token'"
    echo ""
    echo "生成 token: https://github.com/settings/tokens/new"
    echo "  Note: push · Expiration: No expiration · Scopes: 勾 repo"
    exit 1
fi

# ---- 1. 校验 token -------------------------------------------------------
echo "==> 验证 token ..."
ME=$(curl -fsS -H "Authorization: token $TOKEN" https://api.github.com/user \
        | python3 -c "import sys,json; print(json.load(sys.stdin)['login'])" 2>/dev/null || echo "")
if [ "$ME" != "$USER" ]; then
    err "token 校验失败 (返回: '$ME', 期望: '$USER')"
    exit 1
fi
ok "登录账号: $ME"

# ---- 2. 校验仓库 --------------------------------------------------------
echo "==> 验证仓库 $USER/$REPO ..."
HTTP=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$USER/$REPO")
[ "$HTTP" = "200" ] || { err "仓库 HTTP $HTTP"; exit 1; }
ok "仓库存在"

# ---- 3. 推送代码 --------------------------------------------------------
echo "==> 推送 main 分支 ..."
git remote remove origin 2>/dev/null || true
git remote add origin "https://${TOKEN}@github.com/${USER}/${REPO}.git"
if git push -u origin main; then
    ok "推送成功"
else
    err "推送失败"
    exit 1
fi
git remote set-url origin "https://github.com/${USER}/${REPO}.git"

# ---- 4. 开启 Pages -------------------------------------------------------
echo "==> 开启 GitHub Pages ..."
RESP_CODE=$(curl -s -o /tmp/pages_resp.json -w "%{http_code}" -X POST \
    -H "Authorization: token $TOKEN" \
    -H "Accept: application/vnd.github+json" \
    "https://api.github.com/repos/${USER}/${REPO}/pages" \
    -d '{"source":{"branch":"main","path":"/"}}')
RESP=$(cat /tmp/pages_resp.json)
if echo "$RESP" | grep -q '"html_url"'; then
    URL=$(echo "$RESP" | python3 -c "import sys,json; print(json.load(sys.stdin).get('html_url','?'))" 2>/dev/null)
    ok "Pages 已开启 → $URL"
elif echo "$RESP" | grep -qi 'already'; then
    ok "Pages 已经开过了"
else
    warn "开启 Pages 返回 (HTTP $RESP_CODE): $RESP"
fi
rm -f /tmp/pages_resp.json

# ---- 5. 保存 token 到 macOS 钥匙串 (一劳永逸) --------------------------
echo "==> 保存 token 到 macOS 钥匙串 ..."
security delete-generic-password -s "$KEYCHAIN_SERVICE" -a "$KEYCHAIN_ACCOUNT" 2>/dev/null || true
if security add-generic-password -s "$KEYCHAIN_SERVICE" -a "$KEYCHAIN_ACCOUNT" -w "$TOKEN" -U 2>/dev/null; then
    ok "token 已存到钥匙串, 以后推送不用再 paste"
else
    warn "钥匙串保存失败 (不影响本次推送, 以后可能需要重新 paste token)"
fi

# ---- 6. 让 deploy.sh 也能用钥匙串 --------------------------------------
cat > "$SITE_DIR/.deploy-credentials.sh" <<EOF
# Auto-generated by push.sh - do not edit
export GITHUB_TOKEN="$TOKEN"
export GITHUB_USER="$USER"
export GITHUB_REPO="$REPO"
EOF
ok "已生成 .deploy-credentials.sh"

# ---- 7. 完成 ------------------------------------------------------------
sleep 2
STATUS=$(curl -fsS -H "Authorization: token $TOKEN" \
    "https://api.github.com/repos/${USER}/${REPO}/pages" 2>/dev/null \
    | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('status','?'),'·',d.get('html_url',''))" 2>/dev/null \
    || echo "(无法读取)")
ok "Pages 当前状态: $STATUS"

echo ""
echo "========================================================================"
ok "全部搞定!"
echo "  站点: https://${USER}.github.io"
echo "  构建需要 1~2 分钟, 然后访问上面那个网址就能看到网站"
echo ""
echo "  后续改完内容, 推送只需:"
echo "    cd $SITE_DIR"
echo "    ./deploy.sh \"你的改动说明\""
echo "========================================================================"
